function [Ng,Qg] = uo_naics_gen(Q,Node,field)
% function [Ng,Qg] = uo_naics_gen(Q,Node,field)
%
% Accumulates a record of used oil generated by NAICS code.  Uses manifest data
% excluding transfer stations to determine true generation, and generated
% quantities from Node data to account for consolidated generation.

global GEO_REGION
if nargin<3 field='GAL'; end

Ts=unique({Q.TSDF_EPA_ID});
[~,istx]=filter(Q,'GEN_EPA_ID',{@ismember},{Ts});
[~,isimport]=filter(Q,{'GEN_EPA_ID','TSDF_EPA_ID'},{@regexp},{GEO_REGION},{1,0});
isimport=isimport(:,end);

Qg=select(Q(~istx & ~isimport),{'GEN_EPA_ID',field});

Ng=select(Node,{'TSDF_EPA_ID',['G' field]});
Ng=mvfield(Ng,'TSDF_EPA_ID','GEN_EPA_ID');

Qg=[Qg(:); mvfield(Ng(:),['G' field],field)];

Qg=flookup(Qg,'GEN_EPA_ID','NAICS_CODE','bla');

Qg=mvfield(Qg,'NAICS_CODE','GEN_NAICS');

Ng=expand(Qg,'GEN_NAICS',' ',field);
Ng=moddata(Ng,field,@floor);

Ng=accum(Ng,'dam','');
%Qg=ifrmfield(Qg,'Count');

