function [R,MD]=crmfa(year,varargin)
% function [R,MD]=crmfa(year)
%
% Performs the MFA for year x by cross-referencing CR node + manifest data with
% DTSC manifest data.
% 
% Start with just the manifest data and then build outward.
%

tanner_prefix=['../HWTS/Tanner' yy '/'];
tanner_suffix=['_' yy '_221'];

cr_suffix=[ '_' num2str(year)];
if nargin<3
  results_file=['CRMFA' cr_suffix '.mat'];
end

global FACILITIES
if isempty(FACILITIES)
  disp('No Facilities Database.  Attempting to load..')
  ff=check_file('Facilities.mat');
  load(ff);
end

EPAID_DEST_UNKNOWN='CA9999999999';
EPAID_SRC_UNKNOWN='CA0000000000';


DAT=load([tanner_prefix 'MD' tanner_suffix '.mat']);
MD=getfield(DAT,['MD' tanner_suffix]);


[~,I]=filter(MD,'GEN_EPA_ID',{@isempty},[]);
[MD(I).GEN_EPA_ID]=deal(EPAID_SRC_UNKNOWN);
[~,I]=filter(MD,'TSDF_EPA_ID',{@isempty},[]);
[MD(I).TSDF_EPA_ID]=deal(EPAID_DEST_UNKNOWN);
MD=MD(~isnan([MD.TONS])); % drop NaNs

DAT=load([tanner_prefix 'TSDF' tanner_suffix '.mat']);
TSDF=getfield(DAT,['TSDF' tanner_suffix]);

[~,I]=filter(TSDF,'TSDF_BESTMATCH',{@isempty},[]);
[TSDF(I).TSDF_BESTMATCH]=deal(EPAID_DEST_UNKNOWN);
TSDF=mvfield(TSDF,'Accum__TONS','DispTONS');

DAT=load([tanner_prefix 'TxSt' tanner_suffix '.mat']);
TxSt=getfield(DAT,['TxSt' tanner_suffix]);

[~,I]=filter(TxSt,'TSDF_BESTMATCH',{@isempty},[]);
[TxSt(I).TSDF_BESTMATCH]=deal(EPAID_DEST_UNKNOWN);


UE=unique({MD(:).GEN_EPA_ID; MD(:).TSDF_EPA_ID});

%% ----------------------------------------
%
% Ts is a list of TSDFs and their cumulative, error-corrected received tons
% GTs is " " " G+Ts and their cumulative, error-corrected GEN tons
load(crfile)


function R=cruft





%% ########################################################################
%% cruft

% ---------------------------------------------

% now loook at this year's 221 manifests
tanner_prefix=['../HWTS/Tanner' yy '/'];
tanner_suffix=['_' yy '_221'];

tic
disp('Loading TSDF file')
DTSC=load([ tanner_prefix 'TSDF' tanner_suffix ]);
TSDF=DTSC.(['TSDF_' yy '_221']);
TSDF=moddata(TSDF,'Accum__TONS',@floor);
TSDF=mvfield(TSDF,'Accum__TONS','TONS_in');
TSDF=mvfield(TSDF,'TSDF_BESTMATCH','TSDF_EPA_ID');
TSDF=rmfield(TSDF,'WASTE_STATE_CODE');
[TSDF.GAL_in]=deal(0);
TSDF=orderfields(TSDF,[ 3 5 4 2 1]);

%TSDFa=accum(TSDF,'mcadd','');
toc


%% INCOMING: TSDF gives DTSC incoming; 
MAN_D=accum(MAN,'ddmddma','');
MAN_D=mvfield(MAN_D,'GALLONS','GAL_in');
[MAN_D.TONS_in]=deal(0);
MAN_D=orderfields(MAN_D,[1 2 5 3 4]);

INCOMING=sort([MAN_D;TSDF],1);
%keyboard


tic
disp('Loading MD file')
DTSC=load([ tanner_prefix 'MD' tanner_suffix]);

MD=moddata(  DTSC.([ 'MD' tanner_suffix]),     'TONS',@floor);
x=cellfun(@strcmp,{MD.GEN_EPA_ID},{MD.TSDF_EPA_ID});
MD=MD(~x);
[~,nm]=vlookup(MD,'GEN_EPA_ID',INCOMING,'TSDF_EPA_ID','TSDF_EPA_ID');
MD=accum( MD(nm),'mddddma','');
MD=mvfield(MD,'TONS','TONS_out');
[MD.GAL_out]=deal(0);
MD=orderfields(MD,[1 2 3 5 4]);
toc


MAN_S=accum(MAN,'mddddma','');
MAN_S=mvfield(MAN_S,'GALLONS','GAL_out');
[MAN_S.TONS_out]=deal(0);
MAN_S=orderfields(MAN_S,[1 2 5 3 4]);

OUTGOING=sort([MAN_S;MD],1);

MB=accum(INCOMING,'mdaad','');
MB=rmfield( MB, 'Count');
MBb=accum(OUTGOING,'mdaad','');

MB=vlookup(MB,'TSDF_EPA_ID',MBb,'GEN_EPA_ID','TONS_out','zer');
MB=vlookup(MB,'TSDF_EPA_ID',MBb,'GEN_EPA_ID','GAL_out','zer');

MB=orderfields(MB,[2 3 1 4 5]);

NetTons=num2cell([MB(:).TONS_in] - [MB(:).TONS_out]);
[MB.NetTons]=deal(NetTons{:});

NetGal=num2cell([MB(:).GAL_in] - [MB(:).GAL_out]);
[MB.NetGal]=deal(NetGal{:});





% processes the CalRecycle data, that has been conditioned and generated by
% cr_data.m, into a yearly report that can be compared against MDMFA outputs for
% 221.
% Data are saved nominally in 'CRData.mat'
% Default results file is 'CRMFA_yyyy.txt' where yyyy is the year.

%CR_H_a=accum(CR_Hauler,'dmmmdddddddadddddddadaad');
%CR_P_ID=accum(CR_Proc,'ddmmddddddddadddddddaddaddda');

% the idea here is to make an as-close-to-identical report to MDMFA_20xx_221 for
% side-by-side comparison.

showfile=results_file;
if exist(results_file,'file')
  disp(['Deleting results file ' results_file '..'])
  delete(results_file)
end


%% #######################################################################################
%% result tabulation
%% #######################################################################################

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Generation, Imports

%%###### Data 0 - GEN_CA
%% this comes from 


GEN_CA = 0



% this looks into a filtered 2010 list of hauler records and cross-references it
% with a list of transfer reports.  This is problematic in all sorts of ways
% because the hauler records include destination facilities, and the transfer
% reports include a lot of self-transfers to destination facilities
% (e.g. most of ThermoFluids 
H2010_txfrs=sort(accum(H2010,'ddmmdddddddadddddddaadda'),2)
H2010_txfrs=vlookup(H2010_txfrs,'EPAIDNumber',Tx2010_s,'SrcEPAID','Accum__Total','blank')
H2010_txfrs=mvfield(H2010_txfrs,'Accum__Total','HaulerSrcTotal')
H2010_txfrs=vlookup(H2010_txfrs,'EPAIDNumber',Tx2010_d,'DestEPAID','Accum__Total','blank')
H2010_txfrs=mvfield(H2010_txfrs,'Accum__Total','HaulerDestTotal')
%show(H2010_txfrs)

% how to add two structure fields together:
  NetTons=num2cell([GENCNTY_CA(:).Accum__TONS] ...
                   -[GENCNTY_CA(:).Accum__H141_TONS]...
                   +[GENCNTY_CA(:).Accum__H141_SHORT]);
  [GENCNTY_CA.NetTons]=deal(NetTons{:});
