% mfa_activity
% script file to write activity levels to XLS (only works at work)

years=2004:2011;

force=false;
do_xls=false;

if force
  input('Forcing regeneration of md_node data. enter to continue or Ctrl-C to quit','s');
  md_prefix='MD-Tn2_';
  for i=1:length(years)
    for j=1:3
      if exist([md_prefix num2str(years(i)) '_22' num2str(i) '.mat'])==2
        fprintf(1,'Deleting %s%d_22%d.mat...\n',md_prefix,years(i),j);
        delete([md_prefix num2str(years(i)) '_22' num2str(j) '.mat']);
      end
    end
  end
end



clear W Y
filename=['UO-MFA-activity_' datestr(now,'YYYY-mmm-DD') '.xls'];
if do_xls
  Meta=struct('Date',datestr(now),...
              'Units','Gallons, as-reported basis (water content included)',...
              'Conv','301.85 Gal/t (875 g/cm3)',...
              'Columns','',...
              'WC',['California Waste Code: 221 = used oil; 222 = oil/water sludge; '...
                    '223 = other oil-containing waste'],...
              'Facil',['Facility Group description: (G)enerator, (C)onsolidator, ' ...
                      '(Tx)ransfer Station, (P)rocessor'],...
              'ACTIVITY','',...
              'Generated','Generated waste disposed by the given facility group',...
              'Import','Import of waste from out of state',...
              'TxIn','Total inbound transfers',...
              'TxOut','Total outbound transfers (indicates transfer station activity)',...
              'TxLosses','Accounting loss between incoming and outgoing waste',...
              'DK','Apparent waste consumption by DeMenno/Kerdoon',...
              'Ev','Apparent waste consumption by Evergreen Oil',...
              'RFO_CA','Apparent RFO produced within California',...
              'ExportMix','Apparent export of oil out-of-state (to re-refining or RFO)',...
              'Wastewater','Apparent generation of wastewater to processing (H135 plus dewatering)',...
              'HazWaste','Apparent generation of hazardous waste to landfill (H132)',...
              'Incin','Apparent destructive incineration of hazardous waste (H040)',...
              'Rejuv','Estimated reuse or rejuvenation of oil (H129 plus facility-specific knowledge)',...
              'DETAIL','',...
              'TSDF_EPA_ID','EPA ID of disposal facility',...
              'FAC_NAME','Name of facility',...
              'GenGAL','Apparent generation of waste at the facility',...
              'DispGAL','Apparent disposal of waste at the facility',...
              'Others','as above, facility-specific');
  
  
  
  xlswrite(filename,[fieldnames(Meta) struct2cell(Meta)],'Sheet1');
end

W.WC221=[];
W.WC222=[];
W.WC223=[];
for i=1:length(years)
  fprintf(1,'%s %d: ','Gathering MFA data for year',years(i));
  [Ti,Tia]=mfa_lca(years(i));
  Y.(['Y' num2str(years(i))])=sort([Ti{1} Ti{2} Ti{3}],'TSDF_EPA_ID');
  for j=1:3
    W.(['WC22' num2str(j)])=[W.(['WC22' num2str(j)]); Tia{j}];
  end
end

for j=1:3
  W.(['WC22' num2str(j) 's'])=accum(W.(['WC22' num2str(j)]),'mmdaaaaaaaaaaaaad','');
end

if do_xls
  % write spreadsheet
  for j=1:3
    fprintf(1,'%s%d\n','Writing to Excel: WC22',j)
    xlswrite(filename,struct2xls(W.(['WC22' num2str(j) 's'])),...
             ['WC22' num2str(j)]);
  end
  for i=1:length(years)
    fprintf(1,'%s %d %s\n','Writing to Excel: Year',years(i),'detail')
    xlswrite(filename,struct2xls(Y.(['Y' num2str(years(i))])),[num2str(years(i)) ...
                        '_Detail']);
  end
end

  


  
